extends Node

export (PoolStringArray) var synced_properties

func _ready():
	get_parent().add_to_group("synced")
	
	# names containing an @ sign are generated by godot and cannot
	# be synced. We override these and only these with a uuid
	if get_parent().name.find('@') >= 0:
		get_parent().name = Uuid.v4()

func get_sync_state():
	var state = {}
	for property in synced_properties:
		state[property] = get_parent().get(property)
	return state
